-- =============================================================================
--  VHDL instance generated by IPExpress    07/10/2018    23:41:37         
--  Filename: platform1_top_la0_inst.vhd                                          
--  Copyright(c) 2006 Lattice Semiconductor Corporation. All rights reserved.   
-- =============================================================================

-- WARNING - Changes to this file should be performed by re-running IPexpress
-- or modifying the .LPC file and regenerating the core.  Other changes may lead
-- to inconsistent simulation and/or implemenation results */

platform1_top_la0_inst: platform1_top_la0
   port map (
       clk		=> clk,
       reset_n		=> reset_n,
       jtck		=> jtck,
       jrstn		=> jrstn,
       jce2		=> jce2,
       jtdi		=> jtdi,
       er2_tdo		=> er2_tdo,
       jshift		=> jshift,
       jupdate		=> jupdate,
       trigger_din_0	=> trigger_din_0(0 downto 0),
       trace_din	=> trace_din(5 downto 0),
       ip_enable        => ip_enable
)

object /* synthesis GSR=DISABLED */
object /* synthesis UGROUP=”platform1_top_la0_core” */
pragma // attribute UGROUP ”platform1_top_la0_core” 
;

