/* Verilog module instantiation template generated by SCUBA Diamond_2.0_Production (151) */
/* Module Version: 5.4 */
/* Mon Jun 17 12:13:06 2013 */

/* parameterized module instance */
PH_DLY_FIFO __ (.Data( ), .WrClock( ), .RdClock( ), .WrEn( ), .RdEn( ), 
    .Reset( ), .RPReset( ), .Q( ), .Empty( ), .Full( ));
