/* Verilog module instantiation template generated by SCUBA Diamond_2.0_Production (151) */
/* Module Version: 5.3 */
/* Fri Jun 21 10:52:41 2013 */

/* parameterized module instance */
pll_pix2byte __ (.CLKI( ), .RST( ), .CLKOP( ), .CLKOS( ), .CLKOS2( ), 
    .CLKOS3( ), .LOCK( ));
