/* Verilog module instantiation template generated by SCUBA Diamond (64-bit) 3.3.0.109 */
/* Module Version: 5.6 */
/* Thu Apr 02 10:03:15 2015 */

/* parameterized module instance */
pll_pix2byte_RGB888_1lane __ (.CLKI( ), .RST( ), .CLKOP( ), .CLKOS( ), 
    .CLKOS2( ), .LOCK( ));
